Development footer and about page
5-gwoap/adopt-a-family pull request #37
Opened 2017-10-05 02:48 UTC by jwu910

Finishing up work on Footer and added temp link on About us page.

@RebWu 's next issue should redesign the Footer and will revisit then.

2017-10-05 03:18 UTC, jwu910 commented
[4b011e9](https://github.com/5-gwoap/adopt-a-family/pull/37/commits/4b011e9239cce86d398065db6d68e79f5e08ea61) fixes typo on base branch. Import typo preventing build.

2017-10-05 04:51 UTC, rainrivas reviewed
Looks like frontend branch has not been pulled in so the bugs that @psyduc fixed are missing but should be there once we rebase this onto the destination

2017-10-05 04:51 UTC, rainrivas commented on src/components/__tests__/__snapshots__/Footer.test.js.snap
> +      className="footer-text"
@jwu910 I personally prefer this to be on the same line as the icons. E.G. https://gyazo.com/53de944ab4fd43ea5508351473e35ee4
```
<table><tbody><tr><td><a href="https://github.com/5-gwoap" class="social-icon"><i class="fa fa-github fa-2x"></i></a></td><td><div class="footer-text">Code written under <a href="https://opensource.org/licenses/mit-license.html">MIT license</a></div></td><td><a href="mailto:5gwoap@gmail.com" class="social-icon"><i class="fa fa-envelope fa-2x"></i></a></td></tr></tbody></table>
```
> This just moves the license to the middle. Other options are to move it to either end, but this is just personal pref, no deal breaker

2017-10-05 04:51 UTC, rainrivas commented on src/components/__tests__/__snapshots__/Main.test.js.snap
> +  <Footer />
Should this whitespace be here?

2017-10-05 04:51 UTC, rainrivas commented on src/components/Main.js
> +      <Footer />
Should we have this whitespace on closing tags?

2017-10-05 04:55 UTC, rainrivas approved these changes

2017-10-06 18:00 UTC, phuchle requested changes
Overall code is good we may want to use more semantic HTML5 tags like `<header />` and `<footer />`.
Further reading on that:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Content_sectioning

On Ubuntu with Chrome, I'm seeing overflow on the x axis on the landing page.  Also, I'm still seeing the nav issue that duc's branch should have fixed.  Did you merge from frontend-content branch into this one yet?

Josh edit: code styling

2017-10-06 18:16 UTC, jwu910 commented
@phuchle I think this was opened close to when @psyduc had his last changes merged and but i branched out and sent he PR before we had a chance to pull in changes form the base branch frontend-content.

It currently doesn't look like it has duc's latest commits in history

2017-10-07 00:43 UTC, psyduc approved these changes

2017-10-07 01:22 UTC, phuchle approved these changes

2017-10-07 01:25 UTC, merged

2017-10-07 05:07 UTC, jwu910 reviewed
LOL phuc i see what you mean now by using `<footer/>` and `<header/>`