AAF-73 Refactor Input to include html input attribute list
5-gwoap/adopt-a-family pull request #88
Opened 2017-12-20 06:33 UTC by jwu910

2017-12-20 18:08 UTC, jwu910 commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-12-21 21:28 UTC, rainrivas commented
@jwu910 so what's the problem with travis now
`/home/travis/build/5-gwoap/adopt-a-family/src/components/Form.js
  53:12  error  'formTitle' is missing in props validation  react/prop-types`

2017-12-28 06:59 UTC, rainrivas commented
Looks like we only have snapshot errors. @psyduc @phuchle review and it and merge if you can. Otherwise I will do so mañana

2017-12-28 07:48 UTC, jwu910 reviewed
No wonder... goodness

2017-12-29 04:30 UTC, phuchle requested changes

2017-12-29 04:30 UTC, phuchle commented on src/components/Form.js
> +                menuType={STATES}
From looking at just this code, it's not obvious to me what the menuType prop does, so I think we would do well to rename it to something else that is more descriptive.  Maybe `menuData` or `dropdownData`.

2018-01-12 06:12 UTC, phuchle approved these changes

2018-01-12 06:14 UTC, rainrivas approved these changes

2018-01-12 06:14 UTC, merged